#! /usr/bin/env bash

# Configures the dotfiles used by RCM. To see a list of all of the files and their copied
# destinations, run `lsrc`.

# NOTE: Due to the nature of how RCM works, this script can't use `set -euo pipefail`.

EXCLUDES=(
  Brewfile
  rcrc
  readme.md
  stylua.toml
  xterm
)

EXCLUDES="${EXCLUDES[@]}"
DOTFILES_DIRS="$HOME/.dotfiles"
UNDOTTED="Library"
