#!/usr/bin/env bash

set -euo pipefail

POST_UP_HOOKS_DIRECTORY="$(dirname "${BASH_SOURCE[0]}")/post-up-hooks"

source "$POST_UP_HOOKS_DIRECTORY/vim_plugins.sh"
source "$POST_UP_HOOKS_DIRECTORY/vim_spellfile.sh"
source "$POST_UP_HOOKS_DIRECTORY/vim_theme.sh"
source "$POST_UP_HOOKS_DIRECTORY/tmux.sh"
source "$POST_UP_HOOKS_DIRECTORY/nvm.sh"
