#!/bin/bash

# Download Plug
if [ ! -e "$HOME"/.config/nvim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.config/nvim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install the plugins listed in the plugins.vim file
nvim -u "$HOME"/.config/nvim/plugins.vim +PlugInstall +PlugClean! +qa

# Remove the Thoughtbot dotfiles hooks
# https://github.com/thoughtbot/rcm/issues/187
rm -rf $HOME/.thoughtbot_dotfiles/hooks

# Symbolically link the system dictionary to the vim spellfile
ln -s $HOME/Library/Spelling/LocalDictionary $HOME/.vim-spell-en.utf-8.add
