require("landon.settings")
require("landon.keys")
require("landon.plugins")
require("landon.theme")
require("landon.syntax")
require("landon.language")
require("landon.which_key")
require("landon.snippets")
