#!/bin/bash

set -e

# Ensure base16-builder is installed
if ! command -v base16-builder 2>/dev/null; then
  echo "Base16 Builder must be installed!"
  return 1
fi

# Generate the custom theme
mkdir -p $HOME/.config/nvim/themes

base16-builder \
  -t nvim \
  -s $HOME/.dotfiles/themes/landon.yml
  -b light \
  > $HOME/.config/nvim/themes/landon.vim
