[tools]
bun = "latest"
elixir = "latest"
erlang = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
rust = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]
