[tools]
bun = "latest"
elixir = "latest"
erlang = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
uv = "latest"

[settings]
ruby.default_packages_file = "~/.config/mise/default-gems"
idiomatic_version_file_enable_tools = ["node", "ruby", "elixir", "yarn"]
