#!/usr/bin/env ruby

require_relative 'window'
require_relative 'screen'
require_relative 'configuration'
require_relative 'layout'
require_relative 'flashspace'

# Get the current profile and workspace
profile = ARGV[0] || Flashspace.profile
workspace = ARGV[1] || Flashspace.workspace

# Get the workspace configuration
config = Configuration.find_workspace(profile, workspace)

# Get all visible windows, filter them to only those in the workspace configuration and sort
# them by their order in the configuration, then by window ID (oldest to newest)
windows = Window
  .visible
  .filter { config.applications.include?(_1.application) }
  .sort_by { [config.applications.index(_1.application) || config.applications.length, _1.id] }

# Calculate the layout rectangles
rectangles = Layout.calculate(config.layout, Screen.main.visible_rectangle, windows.length)

# Apply the layout to each window
windows.zip(rectangles).each do |window, rectangle|
  window.update_position(rectangle)
end
