#!/usr/bin/env ruby

require_relative 'window'
require_relative 'screen'
require_relative 'configuration'
require_relative 'layout'

# Ensure the correct number of arguments
unless ARGV.length == 2
  warn "Usage: #{$PROGRAM_NAME} <profile> <workspace>"
  exit 1
end

# Get the workspace configuration
config = Configuration.find_workspace(ARGV[0], ARGV[1])

# Get all visible windows, filter them to only those in the workspace configuration and sort
# them by their order in the configuration
windows = Window
  .visible
  .filter { config.applications.include?(_1.application) }
  .sort_by { config.applications.index(_1.application) || config.applications.length }

# Calculate the layout rectangles
rectangles = Layout.calculate(config.layout, Screen.visible_rectangle, windows.length)

# Apply the layout to each window
windows.zip(rectangles).each do |window, rectangle|
  window.update_position(rectangle)
end
