margin: 10.0

# TODO: Ideally, it'd be better to query these values dynamically instead of pre-populating them.
# However, for now, this is simpler and faster.
displays:
  - name: LG HDR 4K
    uuid: 14601E4F-ACEC-49E1-A289-F388BEC05998
    external: true
    menu_bar_height: 31.0
    dock_height: 0.0
  - name: Built-in Retina Display
    uuid: 37D8832A-2D66-02CA-B9F7-8F30A301B230
    external: false
    menu_bar_height: 30.0
    dock_height: 0.0

workspaces:
  - workspace: Browser
    profile: Full
    layout: Fullscreen
    applications: [Arc]

  - workspace: Terminal
    profile: Full
    layout: Fullscreen
    applications: [Ghostty]

  - workspace: Notes
    profile: Full
    layout: Fullscreen
    applications: [Obsidian]

  - workspace: Calendar
    profile: Full
    layout: Fullscreen
    applications: [BusyCal]

  - workspace: Music
    profile: Full
    layout: Fullscreen
    applications: [Spotify, Music]

  - workspace: Slack
    profile: Full
    layout: Fullscreen
    applications: [Slack]

  - workspace: Linear
    profile: Full
    layout: Columns
    applications: [Arc, Linear]

  - workspace: Browser
    profile: Split
    layout: Columns
    applications: [Arc]

  - workspace: Terminal
    profile: Split
    layout: Main Stack
    applications: [Arc, Ghostty]

  - workspace: Notes
    profile: Split
    layout: Main Stack
    applications: [Arc, Obsidian]

  - workspace: Calendar
    profile: Split
    layout: Fullscreen
    applications: [BusyCal]

  - workspace: Music
    profile: Split
    layout: Fullscreen
    applications: [Spotify, Music]

  - workspace: Slack
    profile: Split
    layout: Main Stack
    applications: [Arc, Slack]

  - workspace: Linear
    profile: Split
    layout: Main Stack
    applications: [Arc, Linear]
