margin: 10.0

# TODO: Ideally, it'd be better to query these values dynamically instead of pre-populating them.
# However, for now, this is simpler and faster.
displays:
  - name: LG HDR 4K
    profile: Split
    width: 2560.0
    height: 1440.0
    menu_bar_height: 25.0
    dock_height: 0.0
  - name: Built-in Retina Display
    profile: Full
    width: 1496.0
    height: 967.0
    menu_bar_height: 34.0
    dock_height: 0.0

workspaces:
  - workspace: Browser
    profile: Full
    layout: Fullscreen
    applications: [Arc]

  - workspace: Terminal
    profile: Full
    layout: Fullscreen
    applications: [Ghostty]

  - workspace: Notes
    profile: Full
    layout: Fullscreen
    applications: [Obsidian]

  - workspace: Calendar
    profile: Full
    layout: Fullscreen
    applications: [BusyCal]

  - workspace: Music
    profile: Full
    layout: Fullscreen
    applications: [Spotify, Music]

  - workspace: Slack
    profile: Full
    layout: Fullscreen
    applications: [Slack]

  - workspace: Engineering
    profile: Full
    layout: Columns
    applications: [Ghostty, Obsidian]

  - workspace: Project
    profile: Full
    layout: Fullscreen
    applications: [Linear]

  - workspace: Browser
    profile: Split
    layout: Columns
    applications: [Arc]

  - workspace: Terminal
    profile: Split
    layout: Main Stack
    applications: [Arc, Ghostty]

  - workspace: Notes
    profile: Split
    layout: Main Stack
    applications: [Arc, Obsidian]

  - workspace: Calendar
    profile: Split
    layout: Fullscreen
    applications: [BusyCal]

  - workspace: Music
    profile: Split
    layout: Fullscreen
    applications: [Spotify, Music]

  - workspace: Slack
    profile: Split
    layout: Main Stack
    applications: [Arc, Slack]

  - workspace: Engineering
    profile: Split
    layout: Main Stack
    applications: [Arc, Ghostty, Obsidian]

  - workspace: Project
    profile: Split
    layout: Columns
    applications: [Arc, Ghostty, Linear]
