margin: 10

# TODO: It would be better to query these values dynamically rather than hardcoding them.
menu_bar_height: 34
dock_height: 0

workspaces:
  - workspace: Browser
    profile: Full
    layout: Fullscreen
    applications: [Arc]

  - workspace: Terminal
    profile: Full
    layout: Fullscreen
    applications: [Ghostty]

  - workspace: Notes
    profile: Full
    layout: Fullscreen
    applications: [Obsidian]

  - workspace: Calendar
    profile: Full
    layout: Fullscreen
    applications: [BusyCal]

  - workspace: Music
    profile: Full
    layout: Fullscreen
    applications: [Spotify, Music]

  - workspace: Slack
    profile: Full
    layout: Fullscreen
    applications: [Slack]

  - workspace: Browser
    profile: Split
    layout: Fullscreen
    applications: [Arc]

  - workspace: Terminal
    profile: Split
    layout: Main Stack
    applications: [Arc, Ghostty]

  - workspace: Notes
    profile: Split
    layout: Main Stack
    applications: [Arc, Obsidian]

  - workspace: Calendar
    profile: Split
    layout: Fullscreen
    applications: [BusyCal]

  - workspace: Music
    profile: Split
    layout: Fullscreen
    applications: [Spotify, Music]

  - workspace: Slack
    profile: Split
    layout: Main Stack
    applications: [Arc, Slack]
